import { Inter } from "next/font/google";
import "../globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import Topbar from "@components/layout/Topbar";
import AdBar from "@components/layout/Adbar";
import Leftbar from "@components/layout/Leftbar";
import RightBar from "@components/layout/Rightbar";
import Bottombar from "@components/layout/Bottombar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className} bg-green-1`}>
          <Topbar />
          <AdBar />
          <main className="flex flex-row">
            <Leftbar />
            <section className="main-container">{children}</section>
            <RightBar />
          </main>
          <Bottombar />
        </body>
      </html>
    </ClerkProvider>
  );
}
